KIT-MANAGER-MENU:
  INVENTORY-SIZE: 5
  INVENTORY-TITLE: "&b&lGKit Manager"
  KIT-SELECTION-ACTION-BUTTON-SLOT: 31

KIT-SELECTION-MENU:
  INVENTORY-SIZE: 1
  INVENTORY-TITLE: "&b&lChoose a GKit"
  COOLDOWN-MSG: '&cYou must wait <time-left> to use this kit again.'
  ITEM-LORE:
    NO-PERMS:
      - '&7&m--------------------------'
      - '&cYou can buy this kit in store.frozed.club'
      - '&7&m--------------------------'
    TIME-LEFT:
      - '&7&m--------------------------'
      - '&7Cooldown: &b<kit-cooldown>'
      - ' '
      - '&7Available in: &c<time-left>'
      - '&7Store: &bstore.frozed.club'
      - ' '
      - '&8[&3&l!&8] &7Right-Click to Preview'
      - '&7&m--------------------------'
    AVAILABLE:
      - '&7&m--------------------------'
      - '&7Cooldown: &b<kit-cooldown>'
      - ' '
      - '&aYou can claim this kit now!'
      - '&7Store: &bstore.frozed.club'
      - ' '
      - '&8[&3&l!&8] &7Right-Click to Preview'
      - '&7&m--------------------------'
